export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL_CHANNELS = 'FETCH_ALL_CHANNELS';
export const FETCH_ALL_VIDEOS = 'FETCH_ALL_VIDEOS';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_VIDEO_BY_USER = 'FETCH_VIDEO_BY_USER';
export const FETCH_VIDEO_BY_CATEGORY = 'FETCH_VIDEO_BY_CATEGORY';
export const FETCH_VIDEO_BY_CHANNEL = 'FETCH_VIDEO_BY_CHANNEL';
export const FETCH_CHANNEL_BY_USER = 'FETCH_CHANNEL_BY_USER';
export const FETCH_CHANNEL = 'FETCH_CHANNEL';
export const FETCH_VIDEO = 'FETCH_VIDEO';

export const FETCH_ALL_PROMOTIONS = 'FETCH_ALL_PROMOTIONS';
export const FETCH_PROMOTION = 'FETCH_PROMOTION';
export const FETCH_PROMOTION_BY_USER = 'FETCH_PROMOTION_BY_USER';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const TOGGLE = 'TOGGLE';


export const FETCH_CHANNEL_REQUEST = 'FETCH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';
export const FETCH_VIDEO_REQUEST = 'FETCH_VIDEO_REQUEST';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILURE = 'FETCH_VIDEO_FAILURE';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';

